### ISSUE TITLE
Mongodb storage more selective filter query for `_create_filter`

### ISSUE THREAD

**Issue by ketgo** [kolotaev/vakt#10]
Hi,

As per the current implementation in [link](https://github.com/kolotaev/vakt/blob/657bbac3c964dc5c6d63a5c9a3287a092dfaa431/vakt/storage/mongo.py#L83), the mongodb storage returns all the documents for RegexChecker.This will lead to a performance hit for large number of polices in database. Maybe a temporary solution is to create a more selective query using the following 

```python      
        operator = "$regex"
        conditions = []
        for field in ['subjects', 'resources', 'actions']:
            conditions.append(
                {
                    field: {
                        '$elemMatch': {
                            operator: get_value(field.rstrip('s'))
                        }
                    }
                }
            )
       return {"$or": conditions} #note the use of $or instead of $and
```

till the issue https://jira.mongodb.org/browse/SERVER-11947 is fixed? This way better performance can be achieved at scale. 

Thanks!

**Comment by kolotaev** [comment]
Hi,
Yeh, performance issue for lots of stored policies is what bothers me as well. Things will even get worse when the upcoming feature of https://github.com/kolotaev/vakt/issues/4 is released.

I'm thinking about some kind of cache that is invalidated on policies modification. But it is not even in dev right now.

What concerns the suggested solution for RegexChecker, I'll look at it and figure out if it solves the problem.

**Comment by kolotaev** [comment]
Unfortunately the suggested fix is not feasible. It cuts off some Policies that should be returned for further processing. And it's for a reason - due to the fact that regex match should be against stored patterns, but not the opposite.

Consider the following test. It fails cases: 1, 2, 3:
```python
@pytest.mark.integration
class TestMongoStorage:

    @pytest.fixture()
    def st(self):
        client = create_client()
        yield MongoStorage(client, DB_NAME, collection=COLLECTION)
        client[DB_NAME][COLLECTION].remove()
        client.close()

    @pytest.mark.parametrize('policies, inquiry, expected_reference', [
        (
            [
                Policy(
                    uid=1,
                    actions=['get', 'post'],
                    effect=ALLOW_ACCESS,
                    resources=['<.*>'],
                    subjects=['<[Mm]ax>', '<Jim>']
                ),
            ],
            Inquiry(action='get', resource='printer', subject='Max'),
            True,
        ),
        (
            [
                Policy(
                    uid=1,
                    actions=['<.*>'],
                    effect=ALLOW_ACCESS,
                    resources=['<.*>'],
                    subjects=['<.*>']
                ),
            ],
            Inquiry(action='get', resource='printer', subject='Max'),
            True,
        ),
        (
            [
                Policy(
                    uid=1,
                    actions=['<.*>'],
                    effect=ALLOW_ACCESS,
                    resources=['library:books:<.+>'],
                    subjects=['<.*>']
                ),
            ],
            Inquiry(action='get', resource='library:books:dracula', subject='Max'),
            True,
        ),
        (
            [
                Policy(
                    uid=1,
                    actions=[r'<\d+>'],
                    effect=ALLOW_ACCESS,
                    resources=[r'<\w{1,3}>'],
                    subjects=[r'<\w{2}-\d+>']
                ),
            ],
            Inquiry(action='12', resource='Pie', subject='Jo-1'),
            True,
        ),
    ])
    def test_find_for_inquiry_with_regex_checker(self, st, policies, inquiry, expected_reference):
        mem_storage = MemoryStorage()  # it returns all stored policies so we consider Guard as a reference
        for p in policies:
            st.add(p)
            mem_storage.add(p)

        reference_answer = Guard(mem_storage, RegexChecker()).is_allowed(inquiry)
        assert expected_reference == reference_answer, 'Check reference answer'

        assert reference_answer == Guard(st, RegexChecker()).is_allowed(inquiry), \
            'Mongo storage should give the same answers as reference'
```

Still, I'll say it again, performance issue is what bothers me as well and I'm thinking of the ways to solve it.

**Comment by kolotaev** [comment]
Unfortunately the suggested fix is not feasible. It cuts off some Policies that should be returned for further processing.

Consider the following [test](https://github.com/kolotaev/vakt/blob/6c3b1cec0e3000cad8ea9d3e44029b2fea82664c/tests/test_storage_mongo.py#L190-L252). It fails cases: 1, 2, 3.
Even though currently we do not store compiled regex patterns right now, I've applied the proposed fix and changed storage to save compiled patterns, it still fails. And it's for a reason - due to the fact that regex match should be against stored patterns, but not the opposite (as current mongoDB "$regex" implies).

We can leverage filtering by simple string match for those Policies that use strings as some of their attribute elements instead of regular expressions for situation with Guard that uses RegexChecker, to gain some performance. Probably it can be done in the next release.

**Comment by ketangoyal1988** [comment]
Yes, it might make sense to assign the type of checker to attributes instead of guard. That way at least those with string match can be filtered out by the database.

**Comment by kolotaev** [comment]
@ketgo, I left this issue unclosed on purpose. There are plans to fix this in the future.
Meanwhile, there will be several caching layers that can alleviate the problem in vakt 1.3. If you are interested, here is the [forthcoming docs](https://github.com/kolotaev/vakt/tree/1.3-dev#caching).

That said, let this issue be closed. I'll anyway keep in mind the problem it announces.

**Comment by ketgo** [comment]
Got it, thanks
