### ISSUE TITLE
Is role management supported?

### ISSUE THREAD

**Issue by Rydra** [kolotaev/vakt#15]
Hi there,
I've been peeking through this library to solve a complex authorization problem I have to handle. Looking at the examples, there is one where you use the "role" attribute as subject to assess whether you should give access to a developer or not. In the RBAC system I currently have, users have a role "e.g. developer", and then I inquiry the authorization service with just the username, and then the service automatically resolves that the user is a developer, and then it decides to give you access or not (the request never knows what the role of the user might be).

Is this kind of capability supported? Thank you!

**Comment by kolotaev** [comment]
Hi, since vakt (and ABAC in general) is too generic in this sense, there is no possibility for it to know how to fetch values based on some attribute: e.g. find out that the given username has an admin role by querying some datasource, because combinations of attributes and their meaning is immense, compared to more fine-grained systems like RBAC.

Th only way to do it is to get username the the client side (your app) and pass it as an attribute.

**Comment by Rydra** [comment]
HI @kolotaev, I appreciate your prompt response to my issue :). With your permission I close the issue.

**Comment by kolotaev** [comment]
@Rydra, no problem :)
I just wanted to add that if you need rbac + abac in one bottle you might want to look at casbin and its py-casbin client for python. AFAIK they have both.

**Comment by Rydra** [comment]
@kolotaev Thanks for the lead :D
