### ISSUE TITLE
SQL storage implementation

### ISSUE THREAD

**Issue by kolotaev** [kolotaev/vakt#3]
Since the majority of applications use RDBMS we need to implement SQLStorage to support integration of Vakt into existing apps.
One of the obvious wrapper for that is of course SQLAlchemy.

**Comment by ketgo** [comment]
Is this under development for next release? Since the mongodb storage has performance issues for complex regex based queries, an RDBMS solutions would be the next best thing. For the application I am working on, there will be large number of policies (per resource created) and require failure recovery. Thus a database is required as an in-memory storage is not a viable solution. If this is not under development, I can give it a shot and send a PR.

**Comment by kolotaev** [comment]
@ketgo, it's not under development. It's a next development goal after 1.3 will be released, but I can't guarantee that it will be done soon. That said, if you have a desire and/or time you can try give it a shot, it would be a great contribution!

**Comment by kolotaev** [comment]
The initial implementation of SQLStorage is merged into master with this [PR](https://github.com/kolotaev/vakt/pull/19):

**Comment by kolotaev** [comment]
PR that fixes PyPy sql issues and enables CI for MySQL and Postgres: https://github.com/kolotaev/vakt/pull/22

**Comment by kolotaev** [comment]
Schema and tables adjustments are here: https://github.com/kolotaev/vakt/pull/23

**Comment by kolotaev** [comment]
Regex DB-search is implemented here: https://github.com/kolotaev/vakt/pull/24

**Comment by kolotaev** [comment]
Implemented and released in vakt 1.3.0
